# Deploys multiple stages in one AWS account
name: Build and Deploy-ex4

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Simulate building
        run: sleep 5

      - name: Finish building
        run: echo "Build completed successfully"

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        environment: [ 'dev', 'int', 'prd' ]
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Simulate deployment
        run: sleep 5

      - name: Finish deployment
        run: echo "Deployment completed successfully"